[[GAP_pkg_browse]]
arch = "aarch64"
git-tree-sha1 = "5a69fcc9542fa22c6c5ee9a3d01bc86033aae9d4"
os = "macos"

    [[GAP_pkg_browse.download]]
    sha256 = "57924c0d1fca051c38990cb1b237a1ddb1c905c0e377af3c4ae3b9349a667acf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82200.0+0/GAP_pkg_browse.v101.82200.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_browse]]
arch = "aarch64"
git-tree-sha1 = "539d14cf43c2055bb154f789458ec2b3ec42a54d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_browse.download]]
    sha256 = "6088912eeda7b8f76d2c52bfe9e036ff46a4a84459b996ade3743fff672b695c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82200.0+0/GAP_pkg_browse.v101.82200.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_browse]]
arch = "aarch64"
git-tree-sha1 = "f240f1ea2b05670ab00214d6526a0a0e6d03c1d1"
libc = "musl"
os = "linux"

    [[GAP_pkg_browse.download]]
    sha256 = "76da70256718a42fb2d535068bfa8053dece85dfa58c028be542c84868c6ed7f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82200.0+0/GAP_pkg_browse.v101.82200.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_browse]]
arch = "aarch64"
git-tree-sha1 = "67f125566a934b4d4e5e7d2b756d279ac1ef3348"
os = "freebsd"

    [[GAP_pkg_browse.download]]
    sha256 = "7710679873c29d493a32a3cf3446023fdb1782181410767e034bff9b8eb981ce"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82200.0+0/GAP_pkg_browse.v101.82200.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_browse]]
arch = "powerpc64le"
git-tree-sha1 = "1d52af603b4780e41963edd8d2035fd183113b7f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_browse.download]]
    sha256 = "56b03e172d44f85ef0b3329a0fd292d888a2dc5c91b393f06b73fc834ee420e8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82200.0+0/GAP_pkg_browse.v101.82200.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_browse]]
arch = "riscv64"
git-tree-sha1 = "db1cb1a48e4af41eae188294e1595e87870e5c57"
libc = "glibc"
os = "linux"

    [[GAP_pkg_browse.download]]
    sha256 = "3d5aee1da531fc8c97e030d79f28ae44c62ee98636ceebce8e6bf15f6ed523e5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82200.0+0/GAP_pkg_browse.v101.82200.0.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_browse]]
arch = "x86_64"
git-tree-sha1 = "b86c7a896de689896b7beb43b9f4d280d973c669"
os = "macos"

    [[GAP_pkg_browse.download]]
    sha256 = "f2f6f2ef52aea1a1441ccc1c9765b32c2eb668f22e40bbbb92d6bf6121f20100"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82200.0+0/GAP_pkg_browse.v101.82200.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_browse]]
arch = "x86_64"
git-tree-sha1 = "1e6cec6cbe22f67e42a9d93070385cf0b4d852fc"
libc = "glibc"
os = "linux"

    [[GAP_pkg_browse.download]]
    sha256 = "79a1dd06dfbdca031f25d67e821f1c7df6979d4313f69650bc4223c2b1adfcaf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82200.0+0/GAP_pkg_browse.v101.82200.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_browse]]
arch = "x86_64"
git-tree-sha1 = "e1c61bf7b390500d66de0e5ebfce0379e83d0964"
libc = "musl"
os = "linux"

    [[GAP_pkg_browse.download]]
    sha256 = "90c980f5de65d9a05d208c1cfcaf078d86895ef356b00d71fa9d735ab8326c58"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82200.0+0/GAP_pkg_browse.v101.82200.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_browse]]
arch = "x86_64"
git-tree-sha1 = "d1a30d6a5dfb910928411685dea98bec95894fa5"
os = "freebsd"

    [[GAP_pkg_browse.download]]
    sha256 = "6f0e8b9510b84a09d9398c34cab866d60353982ca3fb8fa68fddbcc4f5186dd4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_browse_jll.jl/releases/download/GAP_pkg_browse-v101.82200.0+0/GAP_pkg_browse.v101.82200.0.x86_64-unknown-freebsd.tar.gz"
